### PR TITLE
Use in-place constraint

### PR DESCRIPTION
**Pull request by tmigot**

### CODE REVIEW

**Comment by tmigot** [comment]
Hi @ocots @amontoison !
I modified a bit the constraint function, so that it does not allocate, and you should see that it changes quite significantly the results of the benchmark for the jacobian.

**Comment by amontoison** [comment]
Great! We beat JuMP on the computation of the Jacobian.
```julia
julia> include("bench.jl")
Hessian of Lagrangian
ADNLP
  3.640 ms (4370 allocations: 8.58 MiB)
JuMP
  59.446 μs (137 allocations: 24.08 KiB)
Jacobian of constraints
ADNLP
  9.438 μs (22 allocations: 20.75 KiB)
JuMP
  15.324 μs (15 allocations: 19.80 KiB)
```

**Comment by ocots** [comment]
Congrats! 

With my computer, under the `main` branch of `ADNLPModels`:

```julia
julia> include("bench.jl")
Hessian of Lagrangian
ADNLP
  4.755 ms (4370 allocations: 8.58 MiB)
JuMP
  82.407 μs (137 allocations: 24.08 KiB)
Jacobian of constraints
ADNLP
  14.831 μs (23 allocations: 21.22 KiB)
JuMP
  20.255 μs (15 allocations: 19.80 KiB)
```

**Comment by amontoison** [comment]
We have a meeting with Tangi this Thursday. We will try to optimize the computation of the Hessian.

**Comment by jbcaillau** [comment]
@tmigot @amontoison great job 👍🏽
- Jacobian ✅
- Hessian: still 50x; actually 10x would be acceptable

As discussed with Alexis, the crucial part for a solver like ipopt (interior point method) is an efficient Hessian computation. And it is much better to have several disjoint but composable backends for AD, ODEs, optimisation, *etc.* than black-box / built-in stuff. Even if it means loosing some performance.

**Pull request merged**
